# Generated by Django 4.1.4 on 2023-01-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sells',
            new_name='Sell',
        ),
    ]
