# Generated by Django 4.1.4 on 2023-01-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0002_rename_sells_sell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
    ]
